const lunch = [{"foodName":"Bhuna Khicuri", "price": 35, "foodImg":"https://i.ibb.co/18jR3qM/bhuna-khicuri.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}, 
{"foodName":"Pakistani Biryani", "price": 60, "foodImg":"https://i.ibb.co/pxyt9ck/Pakistani-Biryani-blog-1-of-1-edited-1-500x500.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}, 
{"foodName":"Panta Ilish", "price": 80, "foodImg":"https://i.ibb.co/vqC9Hyn/panta-ilish.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}, 
{"foodName":"Chicken Biryani", "price": 50, "foodImg":"https://i.ibb.co/8bTJf6H/chicken-biryani.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}, 
{"foodName":"Cinis Pizza", "price": 55, "foodImg":"https://i.ibb.co/BwF1w3Z/cinis-pizza.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}, 
{"foodName":"Italian Pasta", "price": 75, "foodImg":"https://i.ibb.co/wLj5YQz/italian-pasta.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}, 
{"foodName":"Sobji Khichuri", "price": 70, "foodImg":"https://i.ibb.co/GP1cDZV/sobji-khichuri.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}, 
{"foodName":"Food Name", "price": 60, "foodImg":"https://i.ibb.co/xX9c0dd/lunch-1.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}, 
{"foodName":"Hilsa Rice", "price": 75, "foodImg":"https://i.ibb.co/HnTXGcJ/hilsa.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}, 
{"foodName":"Food Name", "price": 65, "foodImg":"https://i.ibb.co/pjnKZhb/dudhersar.webp", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}, 
{"foodName":"Turkey Gravy", "price": 70, "foodImg":"https://i.ibb.co/PN6kJ6q/turkey-gravy.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}, 
{"foodName":"Food Name", "price": 50, "foodImg":"https://i.ibb.co/3c9fWKW/lunch-2.webp", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}

]

export default lunch;