const breakfast = [{"foodName":"Banana Oatmeal", "price": 10, "foodImg":"https://i.ibb.co/RCZSK42/banana-oatmeal.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1", "ingred_2": "Ingredients 2", "ingred_3": "Ingredients 3", "ingred_4": "Ingredients 4", "ingred_5": "Ingredients 5", "ingred_6": "Ingredients 6"}]}, 
{"foodName":"Banshee", "price": 12, "foodImg":"https://i.ibb.co/mJNDgL7/banshee-oneuseonly.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1", "ingred_2": "Ingredients 2", "ingred_3": "Ingredients 3", "ingred_4": "Ingredients 4", "ingred_5": "Ingredients 5", "ingred_6": "Ingredients 6"}]}, 
{"foodName":"Meditartanean Vegan", "price": 20, "foodImg":"https://i.ibb.co/7Jpvkyp/meditarttanean-vegan.webp", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1", "ingred_2": "Ingredients 2", "ingred_3": "Ingredients 3", "ingred_4": "Ingredients 4", "ingred_5": "Ingredients 5", "ingred_6": "Ingredients 6"}]}, 
{"foodName":"Puff Pastry", "price": 10, "foodImg":"https://i.ibb.co/2vh6fys/puff-pastry.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1", "ingred_2": "Ingredients 2", "ingred_3": "Ingredients 3", "ingred_4": "Ingredients 4", "ingred_5": "Ingredients 5", "ingred_6": "Ingredients 6"}]}, 
{"foodName":"Skillet Potatoes", "price": 10, "foodImg":"https://i.ibb.co/KV03p1V/skillet-potatoes.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1", "ingred_2": "Ingredients 2", "ingred_3": "Ingredients 3", "ingred_4": "Ingredients 4", "ingred_5": "Ingredients 5", "ingred_6": "Ingredients 6"}]}, 
{"foodName":"Turkey Breakfast", "price": 18, "foodImg":"https://i.ibb.co/j4hvdhP/turkey-breakfast.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1", "ingred_2": "Ingredients 2", "ingred_3": "Ingredients 3", "ingred_4": "Ingredients 4", "ingred_5": "Ingredients 5", "ingred_6": "Ingredients 6"}]}, 
{"foodName":"Sandwiches", "price": 10, "foodImg":"https://i.ibb.co/R9hQHYZ/sandwiches.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1", "ingred_2": "Ingredients 2", "ingred_3": "Ingredients 3", "ingred_4": "Ingredients 4", "ingred_5": "Ingredients 5", "ingred_6": "Ingredients 6"}]}, 
{"foodName":"Food Name", "price": 10, "foodImg":"https://i.ibb.co/6sLJrgh/breakfast-1.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1", "ingred_2": "Ingredients 2", "ingred_3": "Ingredients 3", "ingred_4": "Ingredients 4", "ingred_5": "Ingredients 5", "ingred_6": "Ingredients 6"}]}, 
{"foodName":"Food Name", "price": 10, "foodImg":"https://i.ibb.co/ChNyHmH/breakfast-2.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1", "ingred_2": "Ingredients 2", "ingred_3": "Ingredients 3", "ingred_4": "Ingredients 4", "ingred_5": "Ingredients 5", "ingred_6": "Ingredients 6"}]}, 
{"foodName":"Card Rice", "price": 15, "foodImg":"https://i.ibb.co/HtNPn58/card-rice.webp", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1", "ingred_2": "Ingredients 2", "ingred_3": "Ingredients 3", "ingred_4": "Ingredients 4", "ingred_5": "Ingredients 5", "ingred_6": "Ingredients 6"}]}, 
{"foodName":"Low Carb", "price": 10, "foodImg":"https://i.ibb.co/s673218/Low-carb.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1", "ingred_2": "Ingredients 2", "ingred_3": "Ingredients 3", "ingred_4": "Ingredients 4", "ingred_5": "Ingredients 5", "ingred_6": "Ingredients 6"}]}, 
{"foodName":"Masala dosa", "price": 15, "foodImg":"https://i.ibb.co/Y8BmgGj/masala-dosa.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1", "ingred_2": "Ingredients 2", "ingred_3": "Ingredients 3", "ingred_4": "Ingredients 4", "ingred_5": "Ingredients 5", "ingred_6": "Ingredients 6"}]}

]

export default breakfast;