const dinner = [{"foodName":"Beef Stew", "price": 35, "foodImg":"https://i.ibb.co/hgtFz2L/beef-stew.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}, 
{"foodName":"Broccoli Polenta", "price": 60, "foodImg":"https://i.ibb.co/xX9H22c/broccoli-polenta.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}, 
{"foodName":"Cnanna Masala", "price": 80, "foodImg":"https://i.ibb.co/bv0hKbf/channa-masala.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}, 
{"foodName":"Chorizo Potatoes", "price": 50, "foodImg":"https://i.ibb.co/ryg901x/chorizo-potatoes.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}, 
{"foodName":"Food Name", "price": 55, "foodImg":"https://i.ibb.co/1s4CGW5/dinner-1q.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}, 
{"foodName":"Food Name", "price": 75, "foodImg":"https://i.ibb.co/8PrVkp7/dinner-2.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}, 
{"foodName":"Honey Farlic", "price": 70, "foodImg":"https://i.ibb.co/0nzpYmb/honey-farlic.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}, 
{"foodName":"Pakistani 2", "price": 60, "foodImg":"https://i.ibb.co/Wy7K78R/pakistani-2.webp", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}, 
{"foodName":"Pakistani ", "price": 75, "foodImg":"https://i.ibb.co/YdKsdnn/pakistani.png", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}, 
{"foodName":"Mongolian Beef", "price": 65, "foodImg":"https://i.ibb.co/NFwxPNx/mongolian-beef.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}, 
{"foodName":"Stedet Vaere", "price": 70, "foodImg":"https://i.ibb.co/dP333F8/stedet-vaere.jpg", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}, 
{"foodName":"Fried Rice", "price": 50, "foodImg":"https://i.ibb.co/mS6qYYZ/fried-rice.webp", "instructions":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ea modi deserunt, numquam pariatur veritatis!", "ingredients": [{"ingred_1": "Ingredients 1"}, {"ingred_2": "Ingredients 2"}, {"ingred_3": "Ingredients 3"}, {"ingred_4": "Ingredients 4"}, {"ingred_5": "Ingredients 5"}, {"ingred_6": "Ingredients 6"}]}

]

export default dinner;